version = 1

# https://kodiakhq.com/docs/recipes#better-merge-messages
[merge.message]
title = "pull_request_title"
include_pr_number = true

https://kodiakhq.com/docs/recipes#adding-pull-request-approvals-to-dependabot-pull-requests
[approve]
# note: remove the "[bot]" suffix from GitHub Bot usernames.
# Instead of "dependabot[bot]" use "dependabot".
auto_approve_usernames = ["allcontributors"]
