name = "kelas-rbagi"
type = "javascript"

account_id = "1d60533bd63392b6dc25160f907c4f76"
zone_id = "f0927dc46f59befdbed0d0be5afcb160"
route = "kelas.rumahberbagi.com/*"
compatibility_date = "2021-12-03"

[site]
bucket = "./public"
entry-point = "."

[build]
command = "npm run build:worker"
watch_dir = "build/index.js"

[build.upload]
format="service-worker"
